version: '3'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db