version: '3'
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  telegram_bot:
    build:
      context: ./src
    volumes:
      - ./bot_logs:/app/logs
    environment:
      # Project:
      DEBUG_MODE: true
      WRITE_LOGS: true
      DEFAULT_TIMEZONE: Europe/Moscow

      # TG bot:
      BOT_TOKEN: ABC
      TG_ADMIN_ID: 123

      # Database:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: db

      # Database main user:
      DB_WG_USER: wg
      DB_WG_PASS: wg

      # Database root schema:
      DB_DEFAULT_SCHEMA_NAME: wg

      # 3x-ui:
      XUI_HOST: http
      XUI_USER: admin
      XUI_PASS: admin
      XUI_VLESS_PORT: 4000
      XUI_MAX_USED_PORTS: 1000

      # Administration:
      BOT_ACCESS_EXPIRED_DELTA_DAYS: 365
      CONF_PAY_EXPIRED_DELTA_DAYS: 30
      FREE_CONF_PERIOD_DAYS: 7
      MAX_CONF_PER_USER: 2
      TG_HELP_CHAT_LINK: https://t.me/123

      # Vless app links:
      VLESS_APP_ANDROID_LINK: https://play.google.com/store/apps/details?id=com.v2raytun.android
      VLESS_APP_APPLE_LINK: https://apps.apple.com/app/id6476628951
      VLESS_APP_PC_LINK: https://github.com/2dust/v2rayN/releases/
      VLESS_APP_ALL_LINK: https://vlesskey.com/download
    depends_on:
      - db
    restart: always

  notifyer:
    build:
      context: ./src/notifyer
      dockerfile: dockerfile
    volumes:
      - ./notifyer_logs:/var/log
    depends_on:
      - telegram_bot
    restart: always