version: '3'
services:
  telegram_bot:
    build:
      context: ./src
    volumes:
      - ./logs:/app/wg_bot_src/logs
    environment:
      DEBUG_MODE: True
      WRITE_LOGS: True
      DEFAULT_TIMEZONE: 'Europe/Moscow'

      BOT_TOKEN: 'ABC'
      TG_ADMIN_ID: 123

      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: db

      DB_WG_USER: wg
      DB_WG_PASS: 'wg'

      DB_DEFAULT_SCHEMA_NAME: wg

      XUI_HOST: 'http'
      XUI_USER: admin
      XUI_PASS: admin
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    restart: always