FROM python:3.13

RUN apt-get update && apt-get install -y cron 

COPY noti /etc/cron.d/
RUN chmod 0644 /etc/cron.d/noti && crontab /etc/cron.d/noti

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD cron -f
