FROM python:3.11-slim

WORKDIR /app/bot

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]  # Замените bot.py на имя вашего файла с кодом бота
